### ISSUE TITLE
Tests randomly fail with "sbt test"

### ISSUE THREAD

**Issue by 22222** [lhartikk/ArnoldC#103]
It looks like the problem is that the tests run in parallel by default.  The tests capture output by globally redirecting standard output to a PrintStream, so if two tests run at the same time then the second test may replace the PrintStream and steal some of the output from the first test.

To avoid this, the solution I've been using is to set "parallelExecution in Test := false" in build.sbt:

```diff
diff --git a/build.sbt b/build.sbt
index 0caf41b..1582e98 100644
--- a/build.sbt
+++ b/build.sbt
@@ -27,3 +27,5 @@ libraryDependencies ++= Seq(
 )
 
 resolvers += "Speech" at "http://maven.it.su.se/it.su.se/maven2"
+
+parallelExecution in Test := false
```

**Comment by lhartikk** [comment]
Thanks!

Fixed.
