### ISSUE TITLE
How to read an integer?

### ISSUE THREAD

**Issue by lmendo** [lhartikk/ArnoldC#113]
Sorry about such basic question but the docummentation is not very clear on that. There's the statement

I WANT TO ASK YOU A BUNCH OF QUESTIONS AND I WANT TO HAVE THEM ANSWERED IMMEDIATELY

but I don't know if it reads from STDIN or elsewhere, and then how to use the read value, for example to assign it to a variable.

Thanks for any advice

**Comment by sjud** [comment]
HEY CHRISTMAS TREE read
YOU SET US UP @NO PROBLEMO
GET YOUR ASS TO MARS read
DO IT NOW
I WANT TO ASK YOU A BUNCH OF QUESTIONS AND I WANT TO HAVE THEM ANSWERED IMMEDIATELY
TALK TO THE HAND read

https://github.com/lhartikk/ArnoldC/blob/master/src/test/scala/org/arnoldc/InputTest.scala

**Comment by lmendo** [comment]
Working! Thanks
