### ISSUE TITLE
[Wiki] Missing space after `#` signs

### ISSUE THREAD

**Issue by hXtreme** [lhartikk/ArnoldC#128]
GitHub flavour markdown requires a space after `#` for it to register as heading. This space is missing at multiple occasions on [this page](https://github.com/lhartikk/ArnoldC/wiki/ArnoldC) 

Demo:

(With space)
#### Foo bar
This automatically generates in-page links in the wiki that help with navigation and sharing on top of adding formatting for heading.

(Without space)
####Foo bar
Here the text is not formatted

**Comment by hXtreme** [comment]
I can just go and fix it once #127 is fixed.

**Comment by lhartikk** [comment]
Thanks for letting be know!

I fixed the wiki
